apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lrv53wfct-go 
  janus-idp.io/tekton: lrv53wfct-go
  backstage.io/kubernetes-id: lrv53wfct-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lrv53wfct-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  