apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lrv53wfct-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lrv53wfct-go 
  name: lrv53wfct-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lrv53wfct-go 
